services:
  db:
    image: postgres:16
    container_name: shop-reservation-db
    environment:
      POSTGRES_USER: shopuser
      POSTGRES_PASSWORD: shop1234
      POSTGRES_DB: shop_reservation
    ports:
      - "5432:5432"
    volumes:
      - shop_reservation_db:/var/lib/postgresql/data

volumes:
  shop_reservation_db:
